In [34]:
from typing import Optional, Tuple
import numpy as np

### Zadanie rozgrzewkowe:
Napisać mnożenie macierzy w ulubionym** języku programowania.

Pytanko: jakie muszą być wymiary mnożonych macierzy? (Który wymiar musi się "zgadzać"?)

Zadanko: Uzupełnić brakujące wymiary macierzy w docstringu (z dokładnością do "alfa-konwersji")

In [35]:
def superfast_matrix_multiply(a: np.matrix, b: np.matrix) -> np.matrix:
    n = a.shape[0]
    m = a.shape[1]
    p = b.shape[1]
    c = np.zeros((n,p))
    
    for i in range(0,n):
        for j in range(0,p):
            for k in range(0,m):
                c[i,j] += a[i,k] * b[k,j]
    return c
    pass

m1 = np.matrix([[1, 2],
                [3, 4],
                [4, 5],
                [5, 1]])

m2 = np.matrix([[1, 2, 3],
                [4, 5, 6]])

res = superfast_matrix_multiply(m1, m2)
np.allclose(res, m1 * m2)

assert np.allclose(res, m1 * m2), "Wrong multiplication result"

### Zadania
1. Przeczytać rozdz. 7. Kincaida i Cheney'a (Systems of Linear Equations).
2. Przeczytać rozdz. 8. Kincaida i Cheney'a (Additional Topics Concerning Systems of Linear Equations).
3. Napisać kod (w ulubionym** języku) do eliminacji Gaussa z i bez pivotingu.
4. Rozwiązać poniższy układ równań z pivotingiem i bez, porównać wyniki

#### Gauss bez pivotingu

In [36]:
def naive_gauss(a, b):
    n = a.shape[0]
    x = np.zeros(n)
    
    for k in range(0,n):
        for i in range(k+1,n):
            xmult = a[i,k] / a[k,k]
            a[i,k] = xmult
            for j in range(k+1,n):
                a[i,j] = a[i,j] - xmult * a[k,j]
            b[i] = b[i] - xmult * b[k]
    x[n-1] = b[n-1] / a[n-1,n-1]
    for i in range(n-1,-1,-1):
        sum = b[i]
        for j in range(i+1,n):
            sum = sum - a[i,j] * x[j]
        x[i] = sum / a[i,i]
    return np.matrix(x).transpose()
    pass

In [37]:
A = np.matrix([[0.0001, -5.0300, 5.8090, 7.8320],
               [2.2660, 1.9950,  1.2120, 8.0080],
               [8.8500, 5.6810,  4.5520, 1.3020],
               [6.7750, -2.253,  2.9080, 3.9700]])

b = np.matrix([9.5740, 7.2190, 5.7300, 6.2910]).transpose()
x1 = np.linalg.solve(A, b)
x = naive_gauss(A, b)
print(x)
np.allclose(x1, x)

[[ 0.21602477]
 [-0.00791511]
 [ 0.63524333]
 [ 0.74617428]]


True

Pytanie: dlaczego wołamy `transpose()` na wektorze `b`? odp.: żeby mieć wektor kolumnowy

Sprawdźmy, czy rozwiązanie jest ok 

(Pytanie': dlaczego po prostu nie użyjemy `==` lub jakiegoś `equals`?) odp.: niedokładność reprezentacji liczb zmiennoprzecinkowych

In [38]:
A = np.matrix([[0.0001, -5.0300, 5.8090, 7.8320],
               [2.2660, 1.9950,  1.2120, 8.0080],
               [8.8500, 5.6810,  4.5520, 1.3020],
               [6.7750, -2.253,  2.9080, 3.9700]])

b = np.matrix([9.5740, 7.2190, 5.7300, 6.2910]).transpose()

np.allclose(np.dot(A, x), b)

True

#### Gauss z pivotingiem 

In [39]:
def pivot_gauss(a, b):
    n = a.shape[0]
    x = np.zeros(n)
    s = np.zeros(n)
    d = np.zeros(n, dtype=np.int)
    
    for i in range(0, n):
        d[i] = i
        smax = 0
        for j in range(0, n):
            smax = max(smax, abs(a[i, j]))
        s[i] = smax
        
    for k in range(0, n - 1):
        rmax = 0
        for i in range(k,n):
            r = abs(a[d[i], k] / s[d[i]])
            if r > rmax:
                rmax = r
                j = i
        tmp = d[j]
        d[j] = d[k]
        d[k] = tmp
        for i in range(k + 1,n):
            xmult = a[d[i], k] / a[d[k], k]
            a[d[i],k] = xmult
            for j in range(k+1, n):
                a[d[i], j] = a[d[i], j] - xmult * a[d[k], j]
    
    for k in range(0,n):
        for i in range(k+1,n):
            b[d[i]] = b[d[i]] - a[d[i], k] * b[d[k]]
    m = n-1
    x[m] = b[d[m]] / a[d[m], m]
    for i in range(n-1, -1, -1):
        sum = b[d[i]]
        for j in range(i+1, n):
            sum = sum - a[d[i], j] * x[j]
        x[i] = sum / a[d[i], i]
    return np.matrix(x).transpose()
    pass

In [40]:
A = np.matrix([[0.0001, -5.0300, 5.8090, 7.8320],
               [2.2660, 1.9950,  1.2120, 8.0080],
               [8.8500, 5.6810,  4.5520, 1.3020],
               [6.7750, -2.253,  2.9080, 3.9700]])

b = np.matrix([9.5740, 7.2190, 5.7300, 6.2910]).transpose()
x1 = np.linalg.solve(A, b)
x = pivot_gauss(A, b)
print(x)
np.allclose(x1, x)

[[ 0.21602477]
 [-0.00791511]
 [ 0.63524333]
 [ 0.74617428]]


True

### Zadania, c.d.
1. Zaimplementować algorytm faktoryzacji LU macierzy
2. (*) Zaimplementować funkcję sprawdzającą, czy dana macierz jest symetryczna i dodatnio określona
    - "symetryczna macierz dodatnio określona $A$ ma rozkład Choleskiego, tzn. istnieje macierz odwracalna $L$, dla której $A = L L^T$ (symetria i dodatnia określoność – to warunki konieczne i dostateczne)" [za: wiki]
3. Zaimplementować algorytm faktoryzacji Cholesky'ego macierzy

In [41]:
def superfast_lu(a: np.matrix) -> Optional[Tuple[np.matrix, np.matrix]]:
    n = a.shape[0]
    l = np.zeros((n,n))
    u = np.zeros((n,n))
    
    for k in range(0,n):
        l[k,k] = 1
        for j in range(k,n):
            sum = 0
            for s in range(0,k):
                sum += l[k,s] * u[s,j]
            u[k,j] = a[k,j] - sum
        for i in range(k+1,n):
            sum = 0
            for s in range(0,k):
                sum += l[i,s] * u[s,k]
            l[i,k] = (a[i,k] - sum) / u[k,k]
    return (l, u)

def superfast_check_spd(a: np.matrix) -> bool:
    l = superfast_cholesky(a)
    llt = superfast_matrix_multiply(l, l.transpose())
    return np.allclose(llt, a)

def superfast_cholesky(a: np.matrix) -> Optional[np.matrix]:
    n = a.shape[0]
    l = np.zeros((n, n))
    
    for k in range(0, n):
        sum = 0
        for s in range(0, k):
            sum += l[k, s] * l[k, s]
        l[k, k] = pow(a[k, k] - sum, 1 / 2)
        for i in range(k+1, n):
            sum = 0
            for s in range(0, k):
                sum += l[i, s] * l[k, s]
            l[i, k] = (a[i, k] - sum) / l[k, k]
    return l

In [42]:
A = np.matrix([[5.0, 3.0, 2.0],
               [ 1.0, 2.0, 0.0],
               [ 3.0, 0.0, 4.0]])

LU = superfast_lu(A)
print(LU[0], " = L")
print(LU[1], " = U")

[[ 1.          0.          0.        ]
 [ 0.2         1.          0.        ]
 [ 0.6        -1.28571429  1.        ]]  = L
[[ 5.          3.          2.        ]
 [ 0.          1.4        -0.4       ]
 [ 0.          0.          2.28571429]]  = U


In [43]:
A = np.matrix([[2.0, -1.0, 0.0],
               [-1.0, 2.0, -1.0],
               [ 0.0, -1.0, 2.0]])

L = superfast_cholesky(A)
print(L, " = L")
print(L.transpose(), " = L^T")

[[ 1.41421356  0.          0.        ]
 [-0.70710678  1.22474487  0.        ]
 [ 0.         -0.81649658  1.15470054]]  = L
[[ 1.41421356 -0.70710678  0.        ]
 [ 0.          1.22474487 -0.81649658]
 [ 0.          0.          1.15470054]]  = L^T


In [44]:
A = np.matrix([[2.0, -1.0, 0.0],
               [-1.0, 2.0,-1.0],
               [ 0.0,-1.0, 2.0]])

superfast_check_spd(A)

True

### Zadania, opcjonalnie
1. zaimplementować metodę Jacobiego (iteracyjne rozwiązywanie układu równań liniowych)
2. za pomocą tejże metody rozwiązać powyższy układ równań

In [45]:
def jacobi_it(a, b):
    ITERATION_LIMIT = 1000
    n = a.shape[0]
    x = np.zeros_like(b)
    
    for it_count in range(ITERATION_LIMIT):
        # print("Current solution:", x)
        x_new = np.zeros_like(x)

        for i in range(0,n):
            s1 = np.dot(a[i, :i], x[:i])
            s2 = np.dot(a[i, i + 1:], x[i + 1:])
            x_new[i] = (b[i] - s1 - s2) / a[i, i]

        if np.allclose(x, x_new, atol=1e-10, rtol=0.):
            break
            
        x = x_new
    return x

In [46]:
A = np.array([[10.0, -1.0, 2.0, 0.0],
              [-1.0, 12.0, -1.0, 3.0],
              [2.0, -1.0, 10.0, -1.0],
              [0.0, 3.0, -1.0, 8.0]])
b = np.array([12.0, 5.0, -11.0, 15.0])

x = jacobi_it(A, b)
print("Solution: ", x)
error = np.dot(A, x) - b
print("Error: ", error)

Solution:  [ 1.44376303  0.00539679 -1.21611677  1.72096161]
Error:  [ 4.80349982e-10 -8.91512641e-10  6.20532958e-10 -6.90013380e-10]


In [47]:
def jacobi_np(a, b):
    x = np.zeros(len(A[0]))
    N = 30
    D = np.diag(A)
    R = A - np.diagflat(D)
    for i in range(N):
        x = (b - np.dot(R,x)) / D
    return x

In [48]:
A = np.array([[10.0, -1.0, 2.0, 0.0],
              [-1.0, 12.0, -1.0, 3.0],
              [2.0, -1.0, 10.0, -1.0],
              [0.0, 3.0, -1.0, 8.0]])
b = np.array([12.0, 5.0, -11.0, 15.0])

x = jacobi_np(A, b)
print("Solution: ", x)
error = np.dot(A, x) - b
print("Error: ", error)

Solution:  [ 1.44376303  0.00539679 -1.21611677  1.72096161]
Error:  [ 1.40207845e-11 -2.60333977e-11  1.81170634e-11 -2.01367811e-11]
